// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/api/proto/ticket.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *GetTicketRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTicketItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketItemRequest) Reset() {
	*x = GetTicketItemRequest{}
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketItemRequest) ProtoMessage() {}

func (x *GetTicketItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketItemRequest.ProtoReflect.Descriptor instead.
func (*GetTicketItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PreGoTicket99999 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreGoTicket99999) Reset() {
	*x = PreGoTicket99999{}
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreGoTicket99999) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreGoTicket99999) ProtoMessage() {}

func (x *PreGoTicket99999) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreGoTicket99999.ProtoReflect.Descriptor instead.
func (*PreGoTicket99999) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *PreGoTicket99999) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreGoTicket99999) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreGoTicket99999) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PreGoTicket99999) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *PreGoTicket99999) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type PreGoTicketItem99999 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StockInitial    int32                  `protobuf:"varint,4,opt,name=stock_initial,json=stockInitial,proto3" json:"stock_initial,omitempty"`
	StockAvailable  int32                  `protobuf:"varint,5,opt,name=stock_available,json=stockAvailable,proto3" json:"stock_available,omitempty"`
	IsStockPrepared bool                   `protobuf:"varint,6,opt,name=is_stock_prepared,json=isStockPrepared,proto3" json:"is_stock_prepared,omitempty"`
	PriceOriginal   float64                `protobuf:"fixed64,7,opt,name=price_original,json=priceOriginal,proto3" json:"price_original,omitempty"`
	PriceFlash      float64                `protobuf:"fixed64,8,opt,name=price_flash,json=priceFlash,proto3" json:"price_flash,omitempty"`
	SaleStartTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sale_start_time,json=saleStartTime,proto3" json:"sale_start_time,omitempty"`
	SaleEndTime     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sale_end_time,json=saleEndTime,proto3" json:"sale_end_time,omitempty"`
	Status          int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	ActivityId      int32                  `protobuf:"varint,12,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreGoTicketItem99999) Reset() {
	*x = PreGoTicketItem99999{}
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreGoTicketItem99999) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreGoTicketItem99999) ProtoMessage() {}

func (x *PreGoTicketItem99999) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreGoTicketItem99999.ProtoReflect.Descriptor instead.
func (*PreGoTicketItem99999) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *PreGoTicketItem99999) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PreGoTicketItem99999) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreGoTicketItem99999) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PreGoTicketItem99999) GetStockInitial() int32 {
	if x != nil {
		return x.StockInitial
	}
	return 0
}

func (x *PreGoTicketItem99999) GetStockAvailable() int32 {
	if x != nil {
		return x.StockAvailable
	}
	return 0
}

func (x *PreGoTicketItem99999) GetIsStockPrepared() bool {
	if x != nil {
		return x.IsStockPrepared
	}
	return false
}

func (x *PreGoTicketItem99999) GetPriceOriginal() float64 {
	if x != nil {
		return x.PriceOriginal
	}
	return 0
}

func (x *PreGoTicketItem99999) GetPriceFlash() float64 {
	if x != nil {
		return x.PriceFlash
	}
	return 0
}

func (x *PreGoTicketItem99999) GetSaleStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleStartTime
	}
	return nil
}

func (x *PreGoTicketItem99999) GetSaleEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleEndTime
	}
	return nil
}

func (x *PreGoTicketItem99999) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PreGoTicketItem99999) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

var File_pkg_api_proto_ticket_proto protoreflect.FileDescriptor

const file_pkg_api_proto_ticket_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/api/proto/ticket.proto\x12\x06ticket\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\x10GetTicketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\x14GetTicketItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xca\x01\n" +
	"\x10PreGoTicket99999\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xdb\x03\n" +
	"\x14PreGoTicketItem99999\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rstock_initial\x18\x04 \x01(\x05R\fstockInitial\x12'\n" +
	"\x0fstock_available\x18\x05 \x01(\x05R\x0estockAvailable\x12*\n" +
	"\x11is_stock_prepared\x18\x06 \x01(\bR\x0fisStockPrepared\x12%\n" +
	"\x0eprice_original\x18\a \x01(\x01R\rpriceOriginal\x12\x1f\n" +
	"\vprice_flash\x18\b \x01(\x01R\n" +
	"priceFlash\x12B\n" +
	"\x0fsale_start_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rsaleStartTime\x12>\n" +
	"\rsale_end_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vsaleEndTime\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1f\n" +
	"\vactivity_id\x18\f \x01(\x05R\n" +
	"activityId2\x9d\x01\n" +
	"\rTicketService\x12K\n" +
	"\rGetTicketItem\x12\x1c.ticket.GetTicketItemRequest\x1a\x1c.ticket.PreGoTicketItem99999\x12?\n" +
	"\tGetTicket\x12\x18.ticket.GetTicketRequest\x1a\x18.ticket.PreGoTicket99999B\x0fZ\rpkg/api/protob\x06proto3"

var (
	file_pkg_api_proto_ticket_proto_rawDescOnce sync.Once
	file_pkg_api_proto_ticket_proto_rawDescData []byte
)

func file_pkg_api_proto_ticket_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_ticket_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_ticket_proto_rawDesc), len(file_pkg_api_proto_ticket_proto_rawDesc)))
	})
	return file_pkg_api_proto_ticket_proto_rawDescData
}

var file_pkg_api_proto_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_proto_ticket_proto_goTypes = []any{
	(*GetTicketRequest)(nil),      // 0: ticket.GetTicketRequest
	(*GetTicketItemRequest)(nil),  // 1: ticket.GetTicketItemRequest
	(*PreGoTicket99999)(nil),      // 2: ticket.PreGoTicket99999
	(*PreGoTicketItem99999)(nil),  // 3: ticket.PreGoTicketItem99999
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_pkg_api_proto_ticket_proto_depIdxs = []int32{
	4, // 0: ticket.PreGoTicket99999.start_time:type_name -> google.protobuf.Timestamp
	4, // 1: ticket.PreGoTicket99999.end_time:type_name -> google.protobuf.Timestamp
	4, // 2: ticket.PreGoTicketItem99999.sale_start_time:type_name -> google.protobuf.Timestamp
	4, // 3: ticket.PreGoTicketItem99999.sale_end_time:type_name -> google.protobuf.Timestamp
	1, // 4: ticket.TicketService.GetTicketItem:input_type -> ticket.GetTicketItemRequest
	0, // 5: ticket.TicketService.GetTicket:input_type -> ticket.GetTicketRequest
	3, // 6: ticket.TicketService.GetTicketItem:output_type -> ticket.PreGoTicketItem99999
	2, // 7: ticket.TicketService.GetTicket:output_type -> ticket.PreGoTicket99999
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_ticket_proto_init() }
func file_pkg_api_proto_ticket_proto_init() {
	if File_pkg_api_proto_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_ticket_proto_rawDesc), len(file_pkg_api_proto_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_ticket_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_ticket_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_ticket_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_ticket_proto = out.File
	file_pkg_api_proto_ticket_proto_goTypes = nil
	file_pkg_api_proto_ticket_proto_depIdxs = nil
}
