// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/api/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserById) Reset() {
	*x = UserById{}
	mi := &file_pkg_api_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserById) ProtoMessage() {}

func (x *UserById) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserById.ProtoReflect.Descriptor instead.
func (*UserById) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserById) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserAccount   string                 `protobuf:"bytes,2,opt,name=user_account,json=userAccount,proto3" json:"user_account,omitempty"`
	UserSalt      string                 `protobuf:"bytes,3,opt,name=user_salt,json=userSalt,proto3" json:"user_salt,omitempty"`
	UserRoles     []*UserRoleType        `protobuf:"bytes,4,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_api_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUserAccount() string {
	if x != nil {
		return x.UserAccount
	}
	return ""
}

func (x *User) GetUserSalt() string {
	if x != nil {
		return x.UserSalt
	}
	return ""
}

func (x *User) GetUserRoles() []*UserRoleType {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

type UserRoleType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoleId          int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName        string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleDescription string                 `protobuf:"bytes,3,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	RoleMenus       []*MenuType            `protobuf:"bytes,4,rep,name=role_menus,json=roleMenus,proto3" json:"role_menus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserRoleType) Reset() {
	*x = UserRoleType{}
	mi := &file_pkg_api_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleType) ProtoMessage() {}

func (x *UserRoleType) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleType.ProtoReflect.Descriptor instead.
func (*UserRoleType) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserRoleType) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserRoleType) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserRoleType) GetRoleDescription() string {
	if x != nil {
		return x.RoleDescription
	}
	return ""
}

func (x *UserRoleType) GetRoleMenus() []*MenuType {
	if x != nil {
		return x.RoleMenus
	}
	return nil
}

type MenuType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuId        int64                  `protobuf:"varint,1,opt,name=menu_id,json=menuId,proto3" json:"menu_id,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	MenuUrl       string                 `protobuf:"bytes,3,opt,name=menu_url,json=menuUrl,proto3" json:"menu_url,omitempty"`
	MenuPrefix    string                 `protobuf:"bytes,4,opt,name=menu_prefix,json=menuPrefix,proto3" json:"menu_prefix,omitempty"`
	MenuPid       string                 `protobuf:"bytes,5,opt,name=menu_pid,json=menuPid,proto3" json:"menu_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuType) Reset() {
	*x = MenuType{}
	mi := &file_pkg_api_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuType) ProtoMessage() {}

func (x *MenuType) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuType.ProtoReflect.Descriptor instead.
func (*MenuType) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *MenuType) GetMenuId() int64 {
	if x != nil {
		return x.MenuId
	}
	return 0
}

func (x *MenuType) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *MenuType) GetMenuUrl() string {
	if x != nil {
		return x.MenuUrl
	}
	return ""
}

func (x *MenuType) GetMenuPrefix() string {
	if x != nil {
		return x.MenuPrefix
	}
	return ""
}

func (x *MenuType) GetMenuPid() string {
	if x != nil {
		return x.MenuPid
	}
	return ""
}

var File_pkg_api_proto_user_proto protoreflect.FileDescriptor

const file_pkg_api_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/api/proto/user.proto\x12\x04user\"#\n" +
	"\bUserById\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x92\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fuser_account\x18\x02 \x01(\tR\vuserAccount\x12\x1b\n" +
	"\tuser_salt\x18\x03 \x01(\tR\buserSalt\x121\n" +
	"\n" +
	"user_roles\x18\x04 \x03(\v2\x12.user.UserRoleTypeR\tuserRoles\"\x9e\x01\n" +
	"\fUserRoleType\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12)\n" +
	"\x10role_description\x18\x03 \x01(\tR\x0froleDescription\x12-\n" +
	"\n" +
	"role_menus\x18\x04 \x03(\v2\x0e.user.MenuTypeR\troleMenus\"\x97\x01\n" +
	"\bMenuType\x12\x17\n" +
	"\amenu_id\x18\x01 \x01(\x03R\x06menuId\x12\x1b\n" +
	"\tmenu_name\x18\x02 \x01(\tR\bmenuName\x12\x19\n" +
	"\bmenu_url\x18\x03 \x01(\tR\amenuUrl\x12\x1f\n" +
	"\vmenu_prefix\x18\x04 \x01(\tR\n" +
	"menuPrefix\x12\x19\n" +
	"\bmenu_pid\x18\x05 \x01(\tR\amenuPid28\n" +
	"\x0fUserServiceGrpc\x12%\n" +
	"\aFindOne\x12\x0e.user.UserById\x1a\n" +
	".user.UserB\x0fZ\rpkg/api/protob\x06proto3"

var (
	file_pkg_api_proto_user_proto_rawDescOnce sync.Once
	file_pkg_api_proto_user_proto_rawDescData []byte
)

func file_pkg_api_proto_user_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_user_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_user_proto_rawDesc), len(file_pkg_api_proto_user_proto_rawDesc)))
	})
	return file_pkg_api_proto_user_proto_rawDescData
}

var file_pkg_api_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_proto_user_proto_goTypes = []any{
	(*UserById)(nil),     // 0: user.UserById
	(*User)(nil),         // 1: user.User
	(*UserRoleType)(nil), // 2: user.UserRoleType
	(*MenuType)(nil),     // 3: user.MenuType
}
var file_pkg_api_proto_user_proto_depIdxs = []int32{
	2, // 0: user.User.user_roles:type_name -> user.UserRoleType
	3, // 1: user.UserRoleType.role_menus:type_name -> user.MenuType
	0, // 2: user.UserServiceGrpc.FindOne:input_type -> user.UserById
	1, // 3: user.UserServiceGrpc.FindOne:output_type -> user.User
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_user_proto_init() }
func file_pkg_api_proto_user_proto_init() {
	if File_pkg_api_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_user_proto_rawDesc), len(file_pkg_api_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_user_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_user_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_user_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_user_proto = out.File
	file_pkg_api_proto_user_proto_goTypes = nil
	file_pkg_api_proto_user_proto_depIdxs = nil
}
