// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: pkg/api/proto/user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserServiceGrpc_FindOne_FullMethodName = "/user.UserServiceGrpc/FindOne"
)

// UserServiceGrpcClient is the client API for UserServiceGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceGrpcClient interface {
	FindOne(ctx context.Context, in *UserById, opts ...grpc.CallOption) (*User, error)
}

type userServiceGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceGrpcClient(cc grpc.ClientConnInterface) UserServiceGrpcClient {
	return &userServiceGrpcClient{cc}
}

func (c *userServiceGrpcClient) FindOne(ctx context.Context, in *UserById, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UserServiceGrpc_FindOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceGrpcServer is the server API for UserServiceGrpc service.
// All implementations must embed UnimplementedUserServiceGrpcServer
// for forward compatibility.
type UserServiceGrpcServer interface {
	FindOne(context.Context, *UserById) (*User, error)
	mustEmbedUnimplementedUserServiceGrpcServer()
}

// UnimplementedUserServiceGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceGrpcServer struct{}

func (UnimplementedUserServiceGrpcServer) FindOne(context.Context, *UserById) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOne not implemented")
}
func (UnimplementedUserServiceGrpcServer) mustEmbedUnimplementedUserServiceGrpcServer() {}
func (UnimplementedUserServiceGrpcServer) testEmbeddedByValue()                         {}

// UnsafeUserServiceGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceGrpcServer will
// result in compilation errors.
type UnsafeUserServiceGrpcServer interface {
	mustEmbedUnimplementedUserServiceGrpcServer()
}

func RegisterUserServiceGrpcServer(s grpc.ServiceRegistrar, srv UserServiceGrpcServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserServiceGrpc_ServiceDesc, srv)
}

func _UserServiceGrpc_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceGrpcServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceGrpc_FindOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceGrpcServer).FindOne(ctx, req.(*UserById))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServiceGrpc_ServiceDesc is the grpc.ServiceDesc for UserServiceGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServiceGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserServiceGrpc",
	HandlerType: (*UserServiceGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOne",
			Handler:    _UserServiceGrpc_FindOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/proto/user.proto",
}
