package main

import (
	"fmt"

	"github.com/gin-gonic/gin"
	_ "github.com/quangdat385/holiday-ticket/communications-service/cmd/swag/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/quangdat385/holiday-ticket/communications-service/global"
	"github.com/quangdat385/holiday-ticket/communications-service/internal/initialize"
	"github.com/quangdat385/holiday-ticket/communications-service/utils/crypto"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           API Documentation Holiday Ticket Communication Service
// @version         1.0.0
// @description     This is a sample server celler server.

// @contact.name   TEAM DATNGUYEN
// @contact.email  datnguyen03011985@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath  /ticket-communication/api/v1
// @schemes   http https

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @type http
// @scheme bearer
// @bearerFormat JWT

// @security BearerAuth

func main() {
	r := initialize.Run()
	r.GET("/ping", func(c *gin.Context) {
		hashKey := crypto.GenerateHash("1", "123456")
		c.JSON(200, gin.H{
			"message": hashKey,
		})
	})
	r.GET("/ticket-communication/api/v1/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	fmt.Println("Starting order service...", global.Config.Server.Port)
	port := fmt.Sprintf(":%d", global.Config.Server.Port)
	r.Run(port) // listen and serve on
}
