// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: 00005_pre_go_communication_media_99999.sql

package database

import (
	"context"
	"database/sql"
)

const deleteCommunicationMedia = `-- name: DeleteCommunicationMedia :execresult
DELETE FROM pre_go_communication_media_99999
WHERE id = ?
`

func (q *Queries) DeleteCommunicationMedia(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCommunicationMedia, id)
}

const getCommunicationMediaById = `-- name: GetCommunicationMediaById :one
SELECT id, message_id, conversation_id, user_id, file_name, original_name, mime_type, size, url, created_at, updated_at
FROM pre_go_communication_media_99999
WHERE id = ?
`

func (q *Queries) GetCommunicationMediaById(ctx context.Context, id int64) (PreGoCommunicationMedia99999, error) {
	row := q.db.QueryRowContext(ctx, getCommunicationMediaById, id)
	var i PreGoCommunicationMedia99999
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ConversationID,
		&i.UserID,
		&i.FileName,
		&i.OriginalName,
		&i.MimeType,
		&i.Size,
		&i.URL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommunicationMediaByMessageId = `-- name: GetCommunicationMediaByMessageId :many
SELECT id, message_id, conversation_id, user_id, file_name, original_name, mime_type, size, url, created_at, updated_at
FROM pre_go_communication_media_99999
WHERE message_id = ?
`

func (q *Queries) GetCommunicationMediaByMessageId(ctx context.Context, messageID sql.NullInt64) ([]PreGoCommunicationMedia99999, error) {
	rows, err := q.db.QueryContext(ctx, getCommunicationMediaByMessageId, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreGoCommunicationMedia99999
	for rows.Next() {
		var i PreGoCommunicationMedia99999
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ConversationID,
			&i.UserID,
			&i.FileName,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommunicationMediaByConversationId = `-- name: GetCommunicationMediaByConversationId :many
SELECT id, message_id, conversation_id, user_id, file_name, original_name, mime_type, size, url, created_at, updated_at
FROM pre_go_communication_media_99999
WHERE conversation_id = ?
LIMIT ? OFFSET ?
`

type GetCommunicationMediaByConversationIdParams struct {
	ConversationID sql.NullInt64
	Limit          int32
	Offset         int32
}

func (q *Queries) GetCommunicationMediaByConversationId(ctx context.Context, arg GetCommunicationMediaByConversationIdParams) ([]PreGoCommunicationMedia99999, error) {
	rows, err := q.db.QueryContext(ctx, getCommunicationMediaByConversationId, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreGoCommunicationMedia99999
	for rows.Next() {
		var i PreGoCommunicationMedia99999
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ConversationID,
			&i.UserID,
			&i.FileName,
			&i.OriginalName,
			&i.MimeType,
			&i.Size,
			&i.URL,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommunicationMedia = `-- name: InsertCommunicationMedia :execresult
INSERT INTO pre_go_communication_media_99999 (
        message_id,
        conversation_id,
        user_id,
        file_name,
        original_name,
        mime_type,
        size,
        url,
        created_at,
        updated_at
    )
VALUES (?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
`

type InsertCommunicationMediaParams struct {
	MessageID      sql.NullInt64
	ConversationID sql.NullInt64
	UserID         int64
	FileName       string
	OriginalName   string
	MimeType       string
	Size           int64
	URL            string
}

func (q *Queries) InsertCommunicationMedia(ctx context.Context, arg InsertCommunicationMediaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertCommunicationMedia,
		arg.MessageID,
		arg.ConversationID,
		arg.UserID,
		arg.FileName,
		arg.OriginalName,
		arg.MimeType,
		arg.Size,
		arg.URL,
	)
}
