// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"encoding/json"
)

// Pre-go communication conversation table
type PreGoCommunicationConversation99999 struct {
	// Primary key
	ID          int64
	Title       sql.NullString
	UserIds     json.RawMessage
	Description sql.NullString
	Type        sql.NullString
	Background  sql.NullString
	Emoji       sql.NullString
	IsDeleted   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// Pre-go communication info table
type PreGoCommunicationInfo99999 struct {
	// Primary key for the communication info table
	ID        int64
	UserID    int64
	Status    sql.NullBool
	Value     string
	Type      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

// ticket pre-go communication message table
type PreGoCommunicationMessage99999 struct {
	// Primary key for the message table
	ID             int64
	ConversationID int64
	UserID         int64
	Status         sql.NullBool
	Message        string
	Type           string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

// notification table
type PreGoCommunicationNotification99999 struct {
	ID        int64
	From      int64
	To        json.RawMessage
	Content   json.RawMessage
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
