export default {
  SEND_VERIFY_EMAIL_SUCCESS: 'Send Verify Email Successfully',
  SEND_FORGET_PASSWORD_EMAIL_SUCCESS: 'Send Forget Password Email Successfully',
  SEND_FORGET_PASSWORD_EMAIL_FAILED: 'Send Forget Password Email Failed',
  SEND_VERIFY_EMAIL_FAILED: 'Send Verify Email Failed',
  USER_NOT_VERIFY: 'User Not Verify',
  EMAIL_EXIST: 'Email Already Exist',
  USER_ALREADY_REGISTER: 'User Already Registered',
  USER_ALREADY_VERIFY: 'User Already Verify',
  USER_NOT_VERIFIED: 'User Not Verified',
  USER_REGISTER_FAIL: 'User Register Failed',
  USER_OTP_NOT_FOUND: 'User Otp Not Found',
  USER_OTP_NOT_MATCH: 'User Otp Not Match',
  USER_VERIFY_NOT_FOUND: 'User Verify Not Found',
  USER_LOGIN_FAIL: 'User Login Failed',
  UPDATE_PASSWORD_REGISTER_FAIL: 'Update Password Register Failed',
  UPDATE_PASSWORD_FORGET_FAIL: 'Update Password Forget Failed',
  UPDATE_PASSWORD_SUCCESS: 'Update Password Successfully',
  CREATE_USER_INFO_REGISTER_FAIL: 'Create User Info Register Failed',
  REFRESH_TONKEN_FAIL: 'Refresh Token Failed',
  TEMPLATE_NOT_FOUND: 'Template Not Found',
  CREATE_USER_SUCCESS: 'Create User Successful',
  CREATE_USER_FAILED: 'Create User Failed',
  CREATE_ACCESS_TOKEN_FAILED: 'Create Access Token Failed',
  GET_USER_SUCCESS: 'Get User Successful',
  TOKEN_EXPIRED: 'Token Expired',
  USER_EXISTING: 'User Already Existing',
  GRANT_ROLE_FAILED: 'Grant Role Failed',
  NOT_FOUND_ROLE: 'Not Found Role',
  CREATE_KEYSTORE_FAILED: 'Create Keystore Failed',
  USER_NOT_FOUND: 'User Not Found',
  CONFIRM_PASSWORD_INVALID: 'Confirm Password Invalid',
  PASSWORD_INVALID: 'Password Incorrect',
  LOGIN_SUCCESS: 'Login Successful',
  LOGOUT_SUCCESS: 'Logout Successful',
  UPDATE_USER_SUCCESS: 'Update Successful',
  DELETE_USER_SUCCESS: 'Delete Successful',
  BLOCK_USER_SUCCESS: 'Block Successful',
  CHANGE_PASSWORD_SUCCESS: 'Change Password Successful',
  UPLOAD_AVATAR_SUCCESS: 'Upload Avatar Successful',
  GET_PROFILE_SUCCESS: 'Get Profile Successful',
  GRANT_ROLE_SUCCESS: 'Grant Role Successful',
  REFRESH_TOCKEN_SUCCESS: 'Refresh Screen Successful',
  CHANGE_STATUS_SUCCESS: 'Change Status Successful',
  TEMPLATE_CREATE_SUCCESS: 'Template Create Successful',
  VERIfY_TOKEN_PASSWORD_SUCCESS: 'Verify Password Successful',
  CREATE_SHOP_SUCCESS: 'Create Shop Successful',
  GET_LIST_SHOP_SUCCESS: 'Get List Shop Successful',
  GET_SHOP_SUCCESS: 'Get Shop Successful',
  UPDATE_SHOP_SUCCESS: 'Update Shop Successful',
  DELETE_SHOP_SUCCESS: 'Delete Shop Successful',
  SOFT_DELETE_SHOP_SUCCESS: 'Soft Delete Shop Successful',
  UPDATE_SHOP_STATUS_SUCCESS: 'Active Shop Successful',
  VERIFY_SHOP_SUCCESS: 'Verify Shop Success',
  CREATE_CONVERSATION_SUCCESS: 'Create Conversation Successful',
  UPDATE_CONVERSATION_SUCCESS: 'Update Conversation Successful',
  CREATE_DISCOUNT_SUCCESS: 'Create Discount Successful',
  UPDATE_DISCOUNT_SUCCESS: 'Update Discount Successful',
  GET_PRODUCT_DISCOUNT_SUCCESS: 'Get Product Discount Successful',
  GET_DISCOUNT_BY_SHOP_SUCCESS: 'Get Product Discount Successful',
  GET_DISCOUNT_AMOUNT_SUCCESS: 'Get Discounts Successful',
  DELETE_DISCOUNT_AMOUNT_SUCCESS: 'Delete Discount Successful',
  PHONE_REGISTER_NOT_SUPPORT: 'Phone Register Not Support'
};
export enum UserStatus {
  BLOCK = 'block',
  PENDING = 'pending',
  ACTIVE = 'active'
}

export enum Action {
  Manage = 'manage',
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete'
}

export enum VerifyType {
  Email = 1,
  Phone = 2
}
